apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins-git
  namespace: argocd
spec:
  destination:
    namespace: ci-cd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ./jenkins-manifest/
    repoURL: https://github.com/IPaul32/Helm-sa2-25-23
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
